---

# introduction

- name: print general info
  debug: msg="{{ role_name }} is executing, on group {{ group_names }}, of server {{ ansible_default_ipv4.address }}"

- name: print role execution info
  debug: msg="site_name {{ site_name }}, site_port {{ site_port }}"

- name: install nginx
  apt: name=nginx state=latest

- name: create nginx config directory
  file: path=/etc/nginx owner={{ ansible_user }} group=root state=directory mode=0644

- name: copy nginx.config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner={{ ansible_user }} group=root backup=yes mode=0644
  notify: restart nginx

- name: make sure nginx service running
  service: name=nginx state=started
