---

# this is the root entry

- hosts: "{{ env }}@webservers"
  gather_facts: False

  tasks:
    - name: executed enviornment
      debug: msg="extra parameter {{ env }}"

  roles:
    #- { role: nginx
    #    , site_name: "read_book"
    #    , site_port: 8080 }
    - { role: "docker"
        , docker_image_name: "ubuntu/nginx"
        , docker_container_name: "web01"
        , docker_container_expose_port: 80
        , docker_host_port: 8080
        , docker_deploy_source_directory: "/Users/jason/temp/"
        , docker_volumes_source_directory: "/var/www/html/"
        , docker_volumes_target_directory: "/var/www/html/"}
