---

# this is the root entry

- hosts: "{{ env }}@webservers"
  gather_facts: False

  tasks:
    - name: executed enviornment
      debug: msg="extra parameter {{ env }}"

  roles:
    - { role: book_online, release_package: "/Users/jason/temp/" }
