---

# introduction

- name: print general info
  debug: msg="{{ role_name }} is executing, on group {{ group_names }}, of server {{ ansible_default_ipv4.address }}"

- name: print role execution info
  debug: msg="firewall_allow_ports {{ firewall_allow_ports }}, firewall_deny_ports {{ firewall_deny_ports }}"

