---

# introduction

- name: print general info
  debug: msg="role {{ role_name }} will be executed, on group {{ group_names }}, of server {{ inventory_hostname }}"

- name: print role execution info
  debug: msg="firewall_allow_ports {{ firewall_allow_ports }}, firewall_deny_ports {{ firewall_deny_ports }}"

