---

# introduction

- name: print general info
  debug: msg="[{{ role_name }}] will be executed, for group [{{ group_names }}], on [{{ inventory_hostname }}]"

- name: print role execution info
  debug: msg="docker_image_name [{{ docker_image_name }}]
              , docker_container_name [{{ docker_container_name }}]
              , docker_container_expose_port [{{ docker_container_expose_port }}]
              , docker_host_port [{{ docker_host_port }}]
              , docker_volumes_source_directory [{{ docker_volumes_source_directory }}]
              , release_package [{{ release_package }}]"

- name: create docker container
  docker_container:
    image: "{{ docker_image_name }}"
    name:  "{{ docker_container_name }}"
    state: started
    restart: yes
    interactive: yes
    volumes:
      "{{ docker_volumes_source_directory }}:{{ docker_volumes_target_directory }}"
    ports:
      - "{{ docker_host_port }}:{{ docker_container_expose_port }}"
