---

# introduction

- name: print general info
  debug: msg="[{{ role_name }}] will be executed, for group [{{ group_names }}], on [{{ inventory_hostname }}]"

- name: print role execution info
  debug: msg="docker_image_name [{{ docker_image_name }}]
              , docker_container_name [{{ docker_container_name }}]
              , docker_container_port_mapping [{{ docker_container_port_mapping }}]
              , docker_copy_source_directory [{{ docker_copy_source_directory }}]
              , docker_copy_target_directory [{{ docker_copy_target_directory }}]"

- name: create docker container
  docker_container:
    image: "{{ docker_image_name }}"
    name:  "{{ docker_container_name }}"
    state: started
    restart: yes
    interactive: yes
    ports:
      - "{{ docker_container_port_mapping }}"

- name: copy files to container
  command: docker exec {{ docker_container_name }} echo "hello Phoenix" > /var/www/html/index.html

- name: start nginx
  command: docker exec web01 nginx
