---

# this is the test for loop

- hosts: webservers
  gather_facts: False

  vars:
    user:
      phoenix:
        name: "phoenix"
        sex: "female"
      jason:
        name: "jason"
        sex: "male"

  tasks:
    - name: 循环
      debug: msg="execute for {{ item }}"
      with_items:
        - one
        - two
      when: "'webservers' in group_names"

    - name: 嵌套
      debug: msg="execute for {{ item[0] }} -----> {{ item[1] }}"
      with_nested:
        - ["A", "B", "C"]
        - ["a", "b", "c", "d"]

    - name: 散列
      debug: msg="name -----> {{ item.key }} value -----> name={{ item.value.name }} sex={{ item.value.sex }}"
      with_dict: "{{ user }}"

    - name: 文件
      debug: msg="files -----> {{ item }}"
      with_fileglob:
        - /private/etc/ansible/playbooks/*.yml

    - name: 随机
      debug: msg="name -----> {{ item }}"
      with_random_choice:
        - "ansible 1"
        - "ansible 2"
        - "ansible 3"

    - name: 命令
      shell: "{{ item }}"
      with_items:
        - hostname
        - uname
      register: ret
    - name: 命令执行结果
      debug: msg="{% for i in ret.results %} {{ i.stdout }} {% endfor %}"


